"""
Django settings for taskmaster project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Prefer environment variable (Heroku config vars). Fall back to local env.py for
# developer convenience, then to a generated dev key.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    try:
        # Try to load SECRET_KEY from a local `env.py` file (not checked into VCS).
        from env import SECRET_KEY as _ENV_SECRET

        SECRET_KEY = _ENV_SECRET
    except Exception:
        # Fallback to the auto-generated key (useful for quick dev setups)
        SECRET_KEY = 'django-insecure--k&p!@%6x3#xgn)#&gd+*)@q2_v(23r==#-)7b6l&$@udi-n&&'

# SECURITY WARNING: don't run with debug turned on in production!
# Explicitly set DEBUG to False for production-safe defaults.
# To enable debugging for local development, set the environment
# variable `DEBUG` to 'True' or override this file.
DEBUG = False

# ALLOWED_HOSTS can be provided as a comma-separated env var (e.g. '.herokuapp.com,example.com')
raw_allowed = os.environ.get('ALLOWED_HOSTS', '')
if raw_allowed:
    ALLOWED_HOSTS = [h.strip() for h in raw_allowed.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',
]

# Crispy Forms (Bootstrap 5) for form rendering
INSTALLED_APPS += [
    'crispy_forms',
    'crispy_bootstrap5',
]

# Use Bootstrap 5 template pack for crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'taskmaster.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'taskmaster.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {}

# Configure database from env.py `DATABASE_URL` or fallback to sqlite3.
try:
    from env import DATABASE_URL
except Exception:
    DATABASE_URL = os.environ.get('DATABASE_URL')

# If running tests, always use a local sqlite database to avoid touching the
# configured Postgres/remote DB. This makes test runs reliable and fast.
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'test_db.sqlite3',
    }
else:
    if DATABASE_URL:
        # Use dj-database-url to parse the URL into Django DATABASES config
        try:
            import dj_database_url

            # conn_max_age helps with persistent connections in production
            DATABASES['default'] = dj_database_url.parse(DATABASE_URL, conn_max_age=600)
        except Exception:
            # If dj_database_url isn't available for some reason, fall back to manual parse
            parsed = urlparse(DATABASE_URL)
            if parsed.scheme.startswith('postgres') or parsed.scheme.startswith('postgresql'):
                DATABASES['default'] = {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': parsed.path[1:],
                    'USER': parsed.username,
                    'PASSWORD': parsed.password,
                    'HOST': parsed.hostname,
                    'PORT': parsed.port or '',
                }
            else:
                DATABASES['default'] = {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': BASE_DIR / 'db.sqlite3',
                }
    else:
        DATABASES['default'] = {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Additional static files settings
# Serve app-level static files in development and support collectstatic for deployment.
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'tasks' / 'static',
]
# Where `collectstatic` will copy files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Use WhiteNoise compressed manifest storage in production for efficient static serving
STATICFILES_STORAGE = os.environ.get(
    'STATICFILES_STORAGE',
    'whitenoise.storage.CompressedManifestStaticFilesStorage',
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Production security settings (can be toggled via env vars)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'True') == 'True'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'True') == 'True'
# Redirect to HTTPS in production if explicitly enabled
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'
